


#spring.datasource.url=jdbc:postgresql://localhost:5432/church_management
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver

## --- JPA/Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

## --- Server ---
#server.port=8080

#spring.datasource.url=jdbc:postgresql://ep-holy-dust-adaot4np-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_OhYfH1vs0VPo

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver




#nube

server.port=${PORT:8080}
#
#spring.datasource.url=jdbc:postgresql://${HOST}:${PORT}/${DATABASE}?sslmode=require
#spring.datasource.username=${USER}
#spring.datasource.password=${PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.show-sql=true